---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/datum_system/datum_system.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/103073/articles/180404/master/file/figures/datum_system/datum_system.svg"
