---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Weldmt - Window Assy 2-2-between/Weldmt - Window Assy 2-2-between.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/103073/articles/180404/master/file/figures/Weldmt%20-%20Window%20Assy%202-2-between/Weldmt%20-%20Window%20Assy%202-2-between.svg"
