(*
   $Id: mim.exp,v 1.16 2020/04/28 23:32:07 lklein Exp $
   ISO TC184/SC4/WG12 N10441 - ISO/TS 10303-1828 wiring_harness_assembly_design - EXPRESS MIM
   Supersedes ISO TC184/SC4/WG12 N10118
*)

SCHEMA Wiring_harness_assembly_design_mim;

USE FROM Edge_based_topological_representation_with_length_constraint_mim;   -- ISO/TS 10303-1830
USE FROM Extruded_structure_cross_section_mim;   -- ISO/TS 10303-1827
USE FROM Wire_and_cable_design_connectivity_mim;   -- ISO/TS 10303-1845

ENTITY harness_node
	SUBTYPE OF (shape_aspect);
END_ENTITY;

ENTITY harness_segment
	SUBTYPE OF (shape_aspect);
END_ENTITY;

  TYPE geometry_association_item_select = EXTENSIBLE GENERIC_ENTITY SELECT (
    cartesian_point,
    curve,
    edge_curve,
    path,
    placement,
    vertex
  );
  END_TYPE; 

  TYPE topology_association_item_select = EXTENSIBLE GENERIC_ENTITY SELECT (
    edge,
    path,
    vertex
  );
  END_TYPE; 

  ENTITY topology_to_geometry_item_association
    SUBTYPE OF (item_defined_transformation);
      SELF\item_defined_transformation.transform_item_1 : topology_association_item_select; 
      SELF\item_defined_transformation.transform_item_2  : geometry_association_item_select;
  END_ENTITY;

  ENTITY geometry_to_topology_item_association
    SUBTYPE OF (item_defined_transformation);
      SELF\item_defined_transformation.transform_item_1 : geometry_association_item_select;
      SELF\item_defined_transformation.transform_item_2  : topology_association_item_select;
  END_ENTITY;

  ENTITY topology_to_geometry_model_association
    SUBTYPE OF (representation_relationship_with_transformation, shape_representation_relationship);
      SELF\representation_relationship_with_transformation.transformation_operator : SET[1:?] OF topology_to_geometry_item_association;
  END_ENTITY;    

  ENTITY geometry_to_topology_model_association
    SUBTYPE OF (representation_relationship_with_transformation, shape_representation_relationship);
    SELF\representation_relationship_with_transformation.transformation_operator : SET[1:?] OF geometry_to_topology_item_association;
  END_ENTITY;    


SUBTYPE_CONSTRAINT whad_item_defined_transformation_subtypes FOR item_defined_transformation;
  ONEOF (topology_to_geometry_item_association, geometry_to_topology_item_association);
END_SUBTYPE_CONSTRAINT;

SUBTYPE_CONSTRAINT whad_representation_relationship_with_transformation_subtypes FOR representation_relationship_with_transformation;
  ONEOF (topology_to_geometry_model_association, geometry_to_topology_model_association);
END_SUBTYPE_CONSTRAINT;

SUBTYPE_CONSTRAINT whad_shape_aspect_subtypes FOR shape_aspect;
          ONEOF (harness_node, harness_segment);
END_SUBTYPE_CONSTRAINT;

END_SCHEMA;
