---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Develop and implement GPS standard - GPS standard development and
      implementation/Develop and implement GPS standard - GPS standard development
      and implementation.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/103073/articles/180404/master/file/figures/Develop%20and%20implement%20GPS%20standard%20-%20GPS%20standard%20development%20and%20implementation/Develop%20and%20implement%20GPS%20standard%20-%20GPS%20standard%20development%20and%20implementation.svg"
