---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/1810-1811-1812-1816/1810-1811-1812-1816.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/103073/articles/180404/master/file/figures/1810-1811-1812-1816/1810-1811-1812-1816.svg"
